services:
  mysql:
    image: mariadb:latest
    container_name: mysql-aino-medical
    env_file:
      - .env.mysql
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-net

  app:
    depends_on:
      mysql:
          condition: service_healthy
    container_name: app-aino-medical
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    ports:
      - 3200:3000
    networks:
      - app-net

  cron:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: cron-aino-medical
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    env_file:
      - .env.local
    networks:
      - app-net


networks:
  app-net:
    name: app-net
