services:
  mysql:
    image: mariadb:latest
    container_name: mysql-aino-medical
    env_file:
      - .env.mysql
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  app:
    depends_on:
      mysql:
          condition: service_started
    container_name: app-aino-medical
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    ports:
      - 3200:3000
    networks:
      - app-net

  cron:
    depends_on:
      mysql:
        condition: service_started
    container_name: cron-aino-medical
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    env_file:
      - .env.local
    networks:
      - app-net


networks:
  app-net:
    name: app-net
