package constant

import (
	"github.com/thoriqwildan/aino-medical-be/internal/entity"
	"github.com/thoriqwildan/aino-medical-be/internal/helper"
)

type row struct {
	Code                string
	Name                string
	Detail              *string
	Limitation          entity.LimitationType
	YearlyBenefitsClaim map[string]*string
	Plafond             map[string]*float64 // by PlanType Name (GRADE X). nil => as charged
}

var DEFAULT_BENEFIT = []row{
	{Code: "RI-1", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Kamar dan Makan (Maks. 365 hari per kasus)"), Limitation: entity.LimitationTypePerDay,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(1500000),
			"PLAN B": helper.PtrFloat64(1000000),
			"PLAN C": helper.PtrFloat64(650000),
			"PLAN D": helper.PtrFloat64(500000),
		},
	},
	{Code: "RI-2", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Perawatan di Rumah Sakit"), Limitation: entity.LimitationTypePerIncident, YearlyBenefitsClaim: map[string]*string{
		"PLAN A": nil,
		"PLAN B": helper.PtrString("RI-PLANB"),
		"PLAN C": helper.PtrString("RI-PLANC"),
		"PLAN D": helper.PtrString("RI-PLAND"),
	},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(20000000),
			"PLAN B": helper.PtrFloat64(13000000),
			"PLAN C": helper.PtrFloat64(10000000),
			"PLAN D": helper.PtrFloat64(8000000),
		},
	},
	{Code: "RI-3", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Kamar Semi ICU dan ICU (Maks. 365 hari per kasus)"), Limitation: entity.LimitationTypePerDay,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(2000000),
			"PLAN B": helper.PtrFloat64(1500000),
			"PLAN C": helper.PtrFloat64(1000000),
			"PLAN D": helper.PtrFloat64(800000),
		},
	},
	{Code: "RI-4", Name: "Rawat Inap", Detail: helper.PtrString("Operasi Kompleks: Biaya Operasi (Termasuk Dokter Bedah, Kamar Operasi dan Anestesi)"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(70000000),
			"PLAN B": helper.PtrFloat64(49000000),
			"PLAN C": helper.PtrFloat64(28000000),
			"PLAN D": helper.PtrFloat64(24500000),
		},
	},
	{Code: "RI-5", Name: "Rawat Inap", Detail: helper.PtrString("Operasi Besar: Biaya Operasi (Termasuk Dokter Bedah, Kamar Operasi dan Anestesi)"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(35000000),
			"PLAN B": helper.PtrFloat64(24500000),
			"PLAN C": helper.PtrFloat64(14000000),
			"PLAN D": helper.PtrFloat64(12250000),
		},
	},
	{Code: "RI-6", Name: "Rawat Inap", Detail: helper.PtrString("Operasi Sedang: Biaya Operasi (Termasuk Dokter Bedah, Kamar Operasi dan Anestesi)"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(22400000),
			"PLAN B": helper.PtrFloat64(15680000),
			"PLAN C": helper.PtrFloat64(8960000),
			"PLAN D": helper.PtrFloat64(7840000),
		},
	},
	{Code: "RI-7", Name: "Rawat Inap", Detail: helper.PtrString("Operasi Kecil: Biaya Operasi (Termasuk Dokter Bedah, Kamar Operasi dan Anestesi)"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(15400000),
			"PLAN B": helper.PtrFloat64(10780000),
			"PLAN C": helper.PtrFloat64(6160000),
			"PLAN D": helper.PtrFloat64(5390000),
		},
	},
	{Code: "RI-8", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Kunjungan Dokter (Maks. 365 hari per kasus)"), Limitation: entity.LimitationTypePerDay,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(500000),
			"PLAN B": helper.PtrFloat64(350000),
			"PLAN C": helper.PtrFloat64(200000),
			"PLAN D": helper.PtrFloat64(175000),
		},
	},
	{Code: "RI-9", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Konsultasi dengan Dokter Spesialis"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(600000),
			"PLAN B": helper.PtrFloat64(450000),
			"PLAN C": helper.PtrFloat64(300000),
			"PLAN D": helper.PtrFloat64(275000),
		},
	},
	{Code: "RI-10", Name: "Rawat Inap", Detail: helper.PtrString("Biaya Ambulan"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": nil,
			"PLAN B": helper.PtrString("RI-PLANB"),
			"PLAN C": helper.PtrString("RI-PLANC"),
			"PLAN D": helper.PtrString("RI-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(500000),
			"PLAN B": helper.PtrFloat64(400000),
			"PLAN C": helper.PtrFloat64(300000),
			"PLAN D": helper.PtrFloat64(250000),
		},
	},
	{Code: "RJ-1", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Konsultasi Dokter Umum"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(140000),
			"PLAN B": helper.PtrFloat64(130000),
			"PLAN C": helper.PtrFloat64(120000),
			"PLAN D": helper.PtrFloat64(100000),
		},
	},
	{Code: "RJ-2", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Konsultasi Dokter Spesialis (Tanpa Surat Pengantar)"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(240000),
			"PLAN B": helper.PtrFloat64(220000),
			"PLAN C": helper.PtrFloat64(200000),
			"PLAN D": helper.PtrFloat64(160000),
		},
	},
	{Code: "RJ-3", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Konsultasi Dokter dan Obat-obatan"), Limitation: entity.LimitationTypePerIncident,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(140000),
			"PLAN B": helper.PtrFloat64(130000),
			"PLAN C": helper.PtrFloat64(120000),
			"PLAN D": helper.PtrFloat64(100000),
		},
	},
	{Code: "RJ-4", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Pembelian Obat-obatan Sesuai dengan Resep Dokter"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(2540000),
			"PLAN B": helper.PtrFloat64(2040000),
			"PLAN C": helper.PtrFloat64(1540000),
			"PLAN D": helper.PtrFloat64(1040000),
		},
	},
	{Code: "RJ-5", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Pemeriksaan Laboratorium"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(2540000),
			"PLAN B": helper.PtrFloat64(2040000),
			"PLAN C": helper.PtrFloat64(1790000),
			"PLAN D": helper.PtrFloat64(1390000),
		},
	},
	{Code: "RJ-6", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Fisioterapi"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(1540000),
			"PLAN B": helper.PtrFloat64(1340000),
			"PLAN C": helper.PtrFloat64(1040000),
			"PLAN D": helper.PtrFloat64(790000),
		},
	},
	{Code: "RJ-7", Name: "Rawat Jalan", Detail: helper.PtrString("Biaya Imunisasi Dasar untuk Anak s/d 5 Tahun"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RJ-PLANA"),
			"PLAN B": helper.PtrString("RJ-PLANB"),
			"PLAN C": helper.PtrString("RJ-PLANC"),
			"PLAN D": helper.PtrString("RJ-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(840000),
			"PLAN B": helper.PtrFloat64(790000),
			"PLAN C": helper.PtrFloat64(640000),
			"PLAN D": helper.PtrFloat64(540000),
		},
	},
	{Code: "RG-1", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Perawatan Dasar"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RG-2", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Perawatan Gusi"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RG-3", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Perawatan Pencegahan"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RG-4", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Perawatan Kompleks"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RG-5", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Perawatan Perbaikan"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RG-6", Name: "Rawat Gigi", Detail: helper.PtrString("Biaya Gigi Palsu"), Limitation: entity.LimitationTypePerYear,
		YearlyBenefitsClaim: map[string]*string{
			"PLAN A": helper.PtrString("RG-PLANA"),
			"PLAN B": helper.PtrString("RG-PLANB"),
			"PLAN C": helper.PtrString("RG-PLANC"),
			"PLAN D": helper.PtrString("RG-PLAND"),
		},
		Plafond: map[string]*float64{
			"PLAN A": nil,
			"PLAN B": nil,
			"PLAN C": nil,
			"PLAN D": nil,
		},
	},
	{Code: "RM-1", Name: "Melahirkan", Detail: helper.PtrString("Biaya Melahirkan Normal"), Limitation: entity.LimitationTypePerPregnancy,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(10000000),
			"PLAN B": helper.PtrFloat64(8500000),
			"PLAN C": helper.PtrFloat64(7000000),
			"PLAN D": helper.PtrFloat64(6750000),
		},
	},
	{Code: "RM-2", Name: "Melahirkan", Detail: helper.PtrString("Biaya Melahirkan dengan Pembedahan (Caesar)"), Limitation: entity.LimitationTypePerPregnancy,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(15000000),
			"PLAN B": helper.PtrFloat64(12000000),
			"PLAN C": helper.PtrFloat64(9000000),
			"PLAN D": helper.PtrFloat64(8500000),
		},
	},
	{Code: "RM-3", Name: "Melahirkan", Detail: helper.PtrString("Biaya Pengguguran Kehamilan (Aborsi) Atas Pertimbangan Medis"), Limitation: entity.LimitationTypePerPregnancy,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(8500000),
			"PLAN B": helper.PtrFloat64(7500000),
			"PLAN C": helper.PtrFloat64(6500000),
			"PLAN D": helper.PtrFloat64(6230000),
		},
	},
	{Code: "RM-4", Name: "Melahirkan", Detail: helper.PtrString("Biaya Komplikasi Kehamilan dan Komplikasi Pasca Melahirkan"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(8500000),
			"PLAN B": helper.PtrFloat64(7500000),
			"PLAN C": helper.PtrFloat64(6500000),
			"PLAN D": helper.PtrFloat64(6230000),
		},
	},
	{Code: "RM-5", Name: "Melahirkan", Detail: helper.PtrString("Biaya Perawatan Sebelum dan 40 Hari Setelah Melahirkan"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(7500000),
			"PLAN B": helper.PtrFloat64(6750000),
			"PLAN C": helper.PtrFloat64(6000000),
			"PLAN D": helper.PtrFloat64(5880000),
		},
	},
	{Code: "RK-1", Name: "Kacamata", Detail: helper.PtrString("Biaya Bingkai Kacamata"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(1250000),
			"PLAN B": helper.PtrFloat64(1000000),
			"PLAN C": helper.PtrFloat64(750000),
			"PLAN D": helper.PtrFloat64(500000),
		},
	},
	{Code: "RK-2", Name: "Kacamata", Detail: helper.PtrString("Biaya Lensa Kacamata atau Lensa Kontak"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(1250000),
			"PLAN B": helper.PtrFloat64(1000000),
			"PLAN C": helper.PtrFloat64(750000),
			"PLAN D": helper.PtrFloat64(500000),
		},
	},
	{Code: "RK-3", Name: "Kacamata", Detail: helper.PtrString("Biaya Refraksi Mata / Konsultasi Dokter Mata"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(250000),
			"PLAN B": helper.PtrFloat64(200000),
			"PLAN C": helper.PtrFloat64(150000),
			"PLAN D": helper.PtrFloat64(150000),
		},
	},
	{Code: "MCU", Name: "Medical Check Up", Detail: helper.PtrString("Biaya Medical Check Up"), Limitation: entity.LimitationTypePerYear,
		Plafond: map[string]*float64{
			"PLAN A": helper.PtrFloat64(1000000),
			"PLAN B": helper.PtrFloat64(800000),
			"PLAN C": helper.PtrFloat64(600000),
			"PLAN D": helper.PtrFloat64(500000),
		},
	},
}

func DefaultBenefit(code string, planType string) *entity.Benefit {
	for _, rw := range DEFAULT_BENEFIT {
		if rw.Code == code {
			return &entity.Benefit{
				Name:           rw.Name,
				Code:           rw.Code,
				Detail:         rw.Detail,
				Plafond:        rw.Plafond[planType],
				LimitationType: rw.Limitation,
			}
		}
	}
	return nil
}
